<?php

namespace Yeomi\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    public function findFive() {
        $query =$this->createQueryBuilder("a")
            ->setMaxResults(5)
            ->where('a.highlight != :true')
            ->setParameter('true', true)
            ->orderBy("a.created", "DESC")
            ->getQuery();

        return $query->getResult();
    }
}
