yeomi_app_newsletter_subscription:
    path:     /newsletter/subscribe
    defaults: { _controller: YeomiAppBundle:App:newsletterSubscribe }

yeomi_app_newsletter_unsubscription:
    path:     /newsletter/unsubscribe
    defaults: { _controller: YeomiAppBundle:App:newsletterUnsubscribe }

yeomi_admin_list_newsletter_subscription:
    path:     /admin/newsletter-subscriptions
    defaults: { _controller: YeomiAppBundle:App:newsletterViewAllAdmin }
