<?php

namespace Yeomi\PostBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

    public function findDefis()
    {
        $query = $this->createQueryBuilder("p")
            ->innerJoin("p.type", "t")
            ->where("t.slug = 'defi'")
            ->getQuery();

        return $query->getResult();

    }
}
