yeomi_cms:
    resource: "@YeomiCMSBundle/Resources/config/routing.yml"
    prefix:   /

yeomi_admin:
    resource: "@YeomiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

yeomi_post:
    resource: "@YeomiPostBundle/Resources/config/routing.yml"
    prefix:   /

yeomi_user:
    resource: "@YeomiUserBundle/Resources/config/routing.yml"
    prefix:   /

login:
   path: /login
   defaults: { _controller: YeomiUserBundle:Main:login }

login_check:
   path: /login_check

logout:
   path: /logout


# HWIOAuthBundle
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /

facebook_login:
    path: /login/check-facebook