security:
    encoders:
        Yeomi\UserBundle\Entity\User:
            algorithm: sha512
            iterations: 1
            encode_as_base64: false


    role_hierarchy:
         ROLE_ADMIN: ROLE_USER
         ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: \Yeomi\UserBundle\Entity\User }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            provider: in_memory
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: login
                check_path: login_check
                use_referer: true
            logout:
                path: logout
                target: yeomi_post_index
            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
