<?php

namespace Yeomi\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Yeomi\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function isUniqueUser(User $user)
    {
        $query = $this->createQueryBuilder("u")
            ->setMaxResults(1)
            ->getQuery();


        return $query->getOneOrNullResult();

    }
}
