yeomi_user_test:
    path:     /tests
    defaults: { _controller: YeomiUserBundle:Main:test }

yeomi_user_register:
    path:     /register
    defaults: { _controller: YeomiUserBundle:Main:register }

yeomi_user_register_success:
    path:     /registration-complete
    defaults: { _controller: YeomiUserBundle:Main:registrationComplete }

yeomi_user_validate:
    path:     /validate/{id}/{token}
    defaults: { _controller: YeomiUserBundle:Main:validate }

yeomi_user_send_mail_validation:
    path:     /send/mail
    defaults: { _controller: YeomiUserBundle:Main:validate }

yeomi_reset_password_validate:
    path:     /reset-password/{id}/{token}
    defaults: { _controller: YeomiUserBundle:Main:resetPasswordValidate }

yeomi_user_password_reset:
    path:     /user/reset
    defaults: { _controller: YeomiUserBundle:Main:resetPassword }

# profile

yeomi_user_profile:
    path:     /profile/{username}
    defaults: { _controller: YeomiUserBundle:Profile:view }

yeomi_user_view_profile:
    path:     /view/profile/{userId}
    defaults: { _controller: YeomiUserBundle:Profile:viewProfile }

yeomi_user_list_activity:
    path:     /list-activity/{userId}
    defaults: { _controller: YeomiUserBundle:Profile:listActivity }

yeomi_user_create_message:
    path:     /create/message/{userId}
    defaults: { _controller: YeomiUserBundle:Profile:createMessage }

yeomi_user_list_message:
    path:     /list/message/{userId}
    defaults: { _controller: YeomiUserBundle:Profile:listMessage }

yeomi_user_view_parameter:
    path:     /view/parameter
    defaults: { _controller: YeomiUserBundle:Profile:viewParameter }